<script setup lang="ts">
import { computed, ref } from 'vue'; import { onLoad } from '@dcloudio/uni-app'
import ConfirmDialog from '@/components/ConfirmDialog.vue'; import StatePanel from '@/components/StatePanel.vue'
import { taskService } from '@/services/tasks'; import { errorMessage } from '@/services/request'; import type { Task, Telemetry } from '@/types/api'; import { canStartTask } from '@/utils/status'
const taskId=ref('');const task=ref<Task|null>(null);const telemetry=ref<Telemetry|null>(null);const note=ref('');const loading=ref(true);const submitting=ref(false);const error=ref('');const confirmVisible=ref(false)
const allowed=computed(()=>task.value?canStartTask(task.value.status):false)
async function load(){loading.value=true;error.value='';try{[task.value,telemetry.value]=await Promise.all([taskService.getTask(taskId.value),taskService.getLatestTelemetry(taskId.value)])}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
async function submit(){if(submitting.value)return;submitting.value=true;try{await taskService.startTask(taskId.value);task.value=await taskService.getTask(taskId.value);confirmVisible.value=false;uni.showToast({title:'发出成功',icon:'success'});setTimeout(()=>uni.navigateBack(),700)}catch(e){confirmVisible.value=false;uni.showToast({title:errorMessage(e),icon:'none',duration:2600})}finally{submitting.value=false}}
onLoad((q)=>{taskId.value=String(q?.task_id||'');if(taskId.value)load();else{loading.value=false;error.value='缺少 task_id'}})
</script>
<template><view class="page"><StatePanel v-if="loading" state="loading"/><StatePanel v-else-if="error" state="error" :message="error" @retry="load"/><template v-else-if="task"><view class="card"><view class="title small">交接核对</view><view class="field row"><text class="label">任务</text><text>{{ task.task_id }}</text></view><view class="field row"><text class="label">样本</text><text>{{ task.sample_name }}</text></view><view class="field row"><text class="label">设备</text><text>{{ task.device_id }}</text></view><view class="field row"><text class="label">接收方</text><text>{{ task.receiver }}</text></view></view><view class="card"><view class="section">初始数据</view><view v-if="telemetry" class="muted">{{ telemetry.temperature }}℃ · 湿度 {{ telemetry.humidity }}% · {{ telemetry.box_status }} · {{ telemetry.move_status }}</view><view v-else class="danger">暂无初始监测数据，请确认设备状态</view></view><view class="card"><view class="section">交接备注（本地核对）</view><textarea v-model="note" maxlength="200" placeholder="选填；当前后端契约不接收备注，不会上传" class="textarea"/><view class="count">{{ note.length }}/200</view></view><button class="primary" :disabled="!allowed||submitting" @tap="confirmVisible=true">{{ allowed ? '确认发出' : '当前状态不可发出' }}</button><ConfirmDialog :visible="confirmVisible" title="确认发出交接？" :content="`任务 ${task.task_id} 发出后将由后端流转为运输中。${note ? '已填写本地核对备注。' : ''}`" :loading="submitting" @cancel="confirmVisible=false" @confirm="submit"/></template></view></template>
<style scoped>.small{font-size:34rpx}.section{font-size:30rpx;font-weight:700;margin-bottom:18rpx}.textarea{width:100%;height:180rpx;background:#f4f7f8;border-radius:14rpx;padding:20rpx;box-sizing:border-box}.count{text-align:right;color:#83918f;font-size:22rpx;margin-top:8rpx}</style>
